import Head from 'next/head'
import Image from 'next/image'
import MainLayout from '@/components/MainLayout'
import Link from 'next/link'
import Landing from './components_Home/1Landing'
import About from './components_Home/2About'
import SectionProp from './components_Home/Allsection/SectionProp'

// import Pages

// import Pages
export default function Home() {


    return (
        <>
            <Head>
                <title>Developer portal</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/myAmges.svg" />
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" />
                <link href="https://fonts.googleapis.com/css2?family=Work+Sans:wght@500;600;700;800&display=swap" rel="stylesheet"></link>
            </Head>

            <MainLayout>
                <>
                    <Landing />
                    <About />
                    <SectionProp />
                </>
            </MainLayout>
        </>
    )
}
