import Head from 'next/head'
import Image from 'next/image'


// import Pages
import Welcome from './components_index/Welcome';
import Login from "./components_index/Login";
// import Pages


export default function Index() {


  return (


    <>
      <Head>
        <title>Developer portal</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/myAmges.svg" />
      </Head>

<h1>dgergjeigj</h1>

      <Welcome />

      <Login />
    </>
  )
}
